// Datos / contenido estático en castellano y euskera

const i18n = {
  es: {
    nav: { philosophy: 'Filosofía', services: 'Servicios', aerotermia: 'Aerotermia', projects: 'Proyectos', process: 'Proceso', contact: 'Contacto' },
    cta: { brief: 'Solicitar cita técnica', call: 'Llamar', whatsapp: 'WhatsApp' },
    hero: {
      eyebrow: 'Reformas integrales · Donostia',
      title: ['Arquitectura técnica', 'para reformas que', 'merecen el ', 'tiempo'],
      titleEm: 'tiempo',
      lede: 'Aparejadores y arquitectos técnicos al frente de cada obra. Diseño, gestión de licencias y dirección integral en el centro de San Sebastián.',
      meta: [
        { k: 'Sede', v: 'Elkano Kalea 1\nDonostia · 20004' },
        { k: 'Desde', v: 'Enero 2025' },
        { k: 'Especialidad', v: 'Reforma integral\n+ aerotermia' },
      ],
    },
    philosophy: {
      num: '01',
      title: ['Tres pilares,', 'una sola ', 'obra.'],
      titleEm: 'obra',
      pillars: [
        {
          n: 'I',
          title: 'Autoridad del aparejador',
          body: 'Cada proyecto está dirigido por un arquitecto técnico colegiado. Estructura, instalaciones y normativa pasan por el filtro de la dirección facultativa antes de tocar un ladrillo.',
        },
        {
          n: 'II',
          title: 'Transparencia en la gestión',
          body: 'Presupuesto cerrado por partidas, cronograma firmado y un único interlocutor desde la primera visita técnica hasta la entrega de llaves.',
        },
        {
          n: 'III',
          title: 'Excelencia en el detalle',
          body: 'Materiales nobles, juntas perfectas, instalaciones embebidas y acabados que se sostienen veinte años. La calidad se ve en lo que no se ve.',
        },
      ],
    },
    services: {
      num: '02',
      title: ['Soluciones', 'integrales para', 'su ', 'patrimonio.'],
      titleEm: 'patrimonio',
      list: [
        { n: '01', name: 'Reforma integral llave en mano', desc: 'Demolición, redistribución, instalaciones y acabados. Gestionamos los gremios y la licencia para que usted reciba la vivienda terminada en la fecha firmada.' },
        { n: '02', name: 'Aerotermia y suelo radiante', desc: 'Sustitución de calderas fósiles por bombas de calor de última generación con suelo radiante refrescante. Hasta un 70 % de ahorro frente a gas natural.' },
        { n: '03', name: 'Reformas de baños y cocinas', desc: 'Cambio de bañera por ducha, baños wellness con materiales pétreos y cocinas a medida con electrodomésticos integrados de gama alta.' },
        { n: '04', name: 'Rehabilitación de viviendas históricas', desc: 'Intervención respetuosa en edificios del Ensanche, el Área Romántica y la Parte Vieja. Refuerzo estructural, aislamiento térmico y acústico.' },
        { n: '05', name: 'Locales comerciales y oficinas', desc: 'Reforma de locales en zona prime con coordinación de la actividad clasificada, ventilación, accesibilidad y diseño de identidad visual del espacio.' },
        { n: '06', name: 'Gestión de licencias y permisos', desc: 'Tramitación íntegra ante el Ayuntamiento de Donostia: comunicación previa, licencia de obra menor o proyecto técnico visado para obra mayor.' },
      ],
    },
    aero: {
      num: '03',
      eyebrow: 'Especialidad técnica',
      headline: ['La eficiencia energética', 'no es una opción.', 'Es la próxima ', 'norma.'],
      headlineEm: 'norma',
      body: 'En Reformas Elkano integramos sistemas de aerotermia con suelo radiante en cada reforma integral. Una sola instalación cubre calefacción, refrigeración y agua caliente sanitaria, extrayendo hasta el 80 % de la energía del aire exterior. La inversión se amortiza en seis a ocho años por el ahorro en factura, y revaloriza el inmueble entre un 15 y un 30 % en el mercado de Donostia.',
      stats: [
        { num: '70', unit: '%', label: 'Reducción media en factura energética anual frente a sistemas con gas natural.' },
        { num: '4.5', unit: 'COP', label: 'Coeficiente de rendimiento medio de las bombas de calor que instalamos.' },
        { num: '25', unit: '%', label: 'Revalorización media del inmueble tras una reforma integral con eficiencia A.' },
        { num: '8', unit: 'años', label: 'Plazo medio de amortización en una vivienda de 100 m² en el centro.' },
      ],
    },
    projects: {
      num: '04',
      title: ['Proyectos', 'recientes,', 'documentados ', 'al detalle.'],
      titleEm: 'detalle',
      filters: ['Todo', 'Centro', 'Gros', 'Antiguo', 'Aiete', 'Locales'],
      list: [
        { tag: 'Reforma integral', neighbourhood: 'Centro', year: '2025', name: 'Piso señorial en San Bartolomé', m2: '142 m²', duration: '4 meses', material: 'Microcemento + roble · Aerotermia Daikin' },
        { tag: 'Aerotermia', neighbourhood: 'Gros', year: '2025', name: 'Ático con vistas a Sagüés', m2: '98 m²', duration: '3 meses', material: 'Suelo radiante refrescante · Carpintería Klein' },
        { tag: 'Baño wellness', neighbourhood: 'Antiguo', year: '2024', name: 'Suite principal en Matia', m2: '18 m²', duration: '5 semanas', material: 'Mármol Calacatta · Grifería Dornbracht' },
        { tag: 'Local comercial', neighbourhood: 'Centro', year: '2024', name: 'Showroom en Elkano 1', m2: '85 m²', duration: '6 semanas', material: 'Tarima nogal · Iluminación lineal Erco' },
      ],
    },
    process: {
      num: '05',
      title: ['Cómo trabajamos.'],
      steps: [
        { num: '01', title: 'Visita técnica', body: 'Aparejador en obra. Mediciones, estado de instalaciones y diagnóstico estructural. Sin compromiso.' },
        { num: '02', title: 'Anteproyecto', body: 'Planos, memoria de calidades y presupuesto cerrado por partidas. Una sola cifra, sin sorpresas.' },
        { num: '03', title: 'Licencias', body: 'Tramitamos comunicación previa o licencia de obra ante el Ayuntamiento. Nos encargamos del visado.' },
        { num: '04', title: 'Ejecución', body: 'Obra coordinada por dirección facultativa. Reportes semanales con fotografías y avance del cronograma.' },
        { num: '05', title: 'Entrega', body: 'Repaso final, manuales, certificados de instalación y garantía decenal. Llaves al cliente.' },
      ],
    },
    team: {
      num: '06',
      quote: ['"Una reforma en Donostia no es solo poner azulejos.', 'Es entender un edificio de 1920, una normativa', 'y un cliente que espera ', 'precisión."'],
      quoteEm: 'precisión',
      author: 'Dirección técnica · Reformas Elkano',
      authorRole: 'ARQ · TÉC · COL.',
      trust: [
        { n: '14', label: 'Proyectos entregados desde 2025' },
        { n: '5.0', label: 'Valoración media en Google' },
        { n: '100', label: '% obras con licencia tramitada' },
        { n: '0', label: 'Sobrecostes en presupuesto cerrado' },
      ],
    },
    contact: {
      num: '07',
      headline: ['Cuéntenos su', 'proyecto. Le', 'visitamos en ', '48 h.'],
      headlineEm: '48 h',
      info: [
        { k: 'Tienda física', v: 'Elkano Kalea 1\n20004 Donostia · Gipuzkoa' },
        { k: 'Teléfono', v: '651 693 689', link: 'tel:+34651693689' },
        { k: 'Correo', v: 'info@reformaselkano.es', link: 'mailto:info@reformaselkano.es' },
        { k: 'Horario', v: 'L–V · 09:00 – 18:30\nSábado con cita previa' },
      ],
    },
    testimonials: {
      num: '06',
      title: ['Lo que dicen', 'quienes ya viven', 'sus ', 'reformas.'],
      titleEm: 'reformas',
      list: [
        { quote: 'Cumplieron al día el plazo firmado y el presupuesto cerrado. La dirección técnica fue impecable: cada semana sabíamos exactamente en qué punto estaba la obra.', author: 'María U.', role: 'Vivienda · Centro · 138 m²', stars: 5 },
        { quote: 'Cambiamos la caldera por aerotermia con suelo radiante y la diferencia en confort y factura es brutal. Nos asesoraron mejor que el ingeniero del edificio.', author: 'Iñaki B.', role: 'Aerotermia · Gros · 95 m²', stars: 5 },
        { quote: 'Tienda física en el centro, presupuesto desglosado por partidas y trato cercano. Tras pedir cuatro presupuestos, fueron los únicos que nos hablaron en plata.', author: 'Carmen y Jorge L.', role: 'Reforma integral · Antiguo', stars: 5 },
        { quote: 'Un baño wellness con materiales pétreos que parecía imposible en 18 m². Acabados perfectos un año después. Volveremos para la cocina.', author: 'Ane S.', role: 'Baño · Aiete · 18 m²', stars: 5 },
      ],
    },
    zone: {
      num: '07',
      title: ['Donostia y', 'alrededores.'],
      lede: 'Trabajamos en toda Gipuzkoa con foco en San Sebastián y municipios limítrofes. Nuestra ubicación física en Elkano 1 nos permite responder visitas técnicas en menos de 48 h en cualquier barrio.',
      areas: [
        { n: 'Centro', desc: 'Ensanche · Área Romántica' },
        { n: 'Gros', desc: 'Sagüés · Egia' },
        { n: 'Antiguo', desc: 'Ondarreta · Matia' },
        { n: 'Aiete', desc: 'Miramón · Lorea' },
        { n: 'Parte Vieja', desc: 'Casco Histórico' },
        { n: 'Amara', desc: 'Berri · Anoeta' },
        { n: 'Hernani', desc: 'Astigarraga · Lasarte' },
        { n: 'Errenteria', desc: 'Pasaia · Oiartzun' },
      ],
    },
    faq: {
      num: '08',
      title: ['Preguntas', 'frecuentes.'],
      list: [
        { q: '¿Cuánto cuesta una reforma integral en Donostia?', a: 'Depende del estado de partida y del nivel de acabados. Como referencia, una reforma integral con materiales de gama media-alta y aerotermia se mueve entre 1.200 € y 1.800 € por m². En la primera visita técnica le entregamos un presupuesto cerrado por partidas, sin sorpresas.' },
        { q: '¿Qué incluye exactamente el presupuesto cerrado?', a: 'Incluye proyecto técnico, gestión de licencias ante el Ayuntamiento, demolición, todas las instalaciones (fontanería, electricidad, climatización), albañilería, carpintería, sanitarios, pavimentos, pintura y dirección facultativa. Si hay imprevistos estructurales, se comunican antes de tocar nada.' },
        { q: '¿Tramitan ustedes la licencia en el Ayuntamiento?', a: 'Sí. Según la magnitud de la obra preparamos comunicación previa, licencia de obra menor o proyecto técnico visado para obra mayor. Conocemos los plazos y las particularidades del Ayuntamiento de Donostia.' },
        { q: '¿Puedo seguir viviendo en la casa durante la obra?', a: 'En reformas integrales lo desaconsejamos por seguridad y polvo. Si solo se reforman baño o cocina, planificamos las fases para que pueda permanecer. Le ayudamos a estimar el tiempo y los costes de un alquiler temporal.' },
        { q: '¿Cuánto tarda una reforma integral?', a: 'Una vivienda media de 90–120 m² requiere entre 12 y 16 semanas de obra desde la concesión de la licencia. El plazo se firma en contrato y se traduce en penalización por demora si la causa es imputable a nosotros.' },
        { q: '¿Qué garantía dan las obras?', a: 'Diez años de garantía decenal en elementos estructurales (Ley de Ordenación de la Edificación), tres años en elementos constructivos y un año en acabados. Toda la documentación queda en su poder al finalizar.' },
      ],
    },
    footer: {
      legal: ['Aviso legal', 'Política de privacidad', 'Cookies'],
      copy: '© 2025–2026 Reformas Elkano · Elkano Kalea 1, 20004 Donostia',
    },
    marquee: ['Reformas integrales', 'Aerotermia + suelo radiante', 'Aparejadores colegiados', 'Presupuesto cerrado', 'Obra mayor y obra menor', 'San Sebastián Shops', 'Eficiencia energética A'],
  },
  eu: {
    nav: { philosophy: 'Filosofia', services: 'Zerbitzuak', aerotermia: 'Aerotermia', projects: 'Proiektuak', process: 'Prozesua', contact: 'Kontaktua' },
    cta: { brief: 'Eskatu bisita teknikoa', call: 'Deitu', whatsapp: 'WhatsApp' },
    hero: {
      eyebrow: 'Erreforma integralak · Donostia',
      title: ['Arkitektura teknikoa', 'denbora merezi', 'duten ', 'erreformetarako'],
      titleEm: 'denbora',
      lede: 'Aparejadoreak eta arkitekto teknikoak obra bakoitzaren buruan. Diseinua, lizentzien kudeaketa eta zuzendaritza integrala Donostiako erdigunean.',
      meta: [
        { k: 'Egoitza', v: 'Elkano Kalea 1\nDonostia · 20004' },
        { k: 'Hasiera', v: '2025eko urtarrila' },
        { k: 'Espezialitatea', v: 'Erreforma integrala\n+ aerotermia' },
      ],
    },
    philosophy: {
      num: '01',
      title: ['Hiru zutabe,', 'obra ', 'bakarra.'],
      titleEm: 'bakarra',
      pillars: [
        { n: 'I', title: 'Aparejadorearen autoritatea', body: 'Proiektu bakoitza arkitekto tekniko kolegiatu batek zuzentzen du. Egitura, instalazioak eta araudia zuzendaritza fakultatiboaren iragazkitik pasatzen dira adreilurik ukitu aurretik.' },
        { n: 'II', title: 'Kudeaketan gardentasuna', body: 'Aurrekontu itxia partidaka, sinatutako kronograma eta solaskide bakarra lehen bisita teknikotik giltzak emateraino.' },
        { n: 'III', title: 'Xehetasunaren bikaintasuna', body: 'Material nobleak, junturaren perfekzioa, instalazio txertatuak eta hogei urte irauten duten akaberak. Kalitatea ikusten ez denean ikusten da.' },
      ],
    },
    services: {
      num: '02',
      title: ['Zure ondarearen', 'soluzio ', 'integralak.'],
      titleEm: 'integralak',
      list: [
        { n: '01', name: 'Erreforma integrala giltzaz giltza', desc: 'Eraisketa, banaketa, instalazioak eta akaberak. Gremioak eta lizentzia kudeatzen ditugu, etxebizitza amaituta jaso dezazun sinatutako datan.' },
        { n: '02', name: 'Aerotermia eta zoru irradiatzailea', desc: 'Galdara fosilen ordez azken belaunaldiko bero-ponpak zoru irradiatzaile freskagarriarekin. % 70eko aurrezpena gas naturalaren aurrean.' },
        { n: '03', name: 'Bainugela eta sukaldeen erreforma', desc: 'Bainuontzia dutxara aldatzea, bainugela wellness harrizko materialekin eta sukalde neurrira goi mailako etxetresnekin.' },
        { n: '04', name: 'Etxebizitza historikoen birgaitzea', desc: 'Esku-hartze errespetuzkoa Erdialdean, Erromantizismoaren Aldean eta Alde Zaharrean. Egitura indartzea, isolamendu termiko eta akustikoa.' },
        { n: '05', name: 'Lokal komertzialak eta bulegoak', desc: 'Lokal erreformak gune nagusian, jarduera klasifikatuaren koordinazio osoarekin, aireztapena, irisgarritasuna eta espazioaren nortasuna.' },
        { n: '06', name: 'Lizentzien eta baimenen kudeaketa', desc: 'Donostiako Udalaren aurrean osoko izapidetzea: aurretiazko komunikazioa, obra txikiko lizentzia edo obra handirako proiektu tekniko bisatua.' },
      ],
    },
    aero: {
      num: '03',
      eyebrow: 'Espezialitate teknikoa',
      headline: ['Eraginkortasun energetikoa', 'ez da aukera bat.', 'Hurrengo ', 'araua da.'],
      headlineEm: 'araua',
      body: 'Reformas Elkanon aerotermia eta zoru irradiatzaile sistemak integratzen ditugu erreforma integral bakoitzean. Instalazio bakar batek berokuntza, hozketa eta ur bero sanitarioa estaltzen ditu, kanpoko airearen energiaren % 80raino erauziz. Inbertsioa sei-zortzi urtean amortizatzen da fakturan aurrezteagatik, eta higiezina % 15 eta % 30 artean baloratzen du Donostiako merkatuan.',
      stats: [
        { num: '70', unit: '%', label: 'Faktura energetikoaren urteko murrizketa media gas naturalaren aurrean.' },
        { num: '4.5', unit: 'COP', label: 'Instalatzen ditugun bero-ponpen errendimendu koefiziente media.' },
        { num: '25', unit: '%', label: 'Higiezinaren batez besteko balorazioa A eraginkortasunaren ondoren.' },
        { num: '8', unit: 'urte', label: 'Erdiguneko 100 m²-ko etxebizitza batean amortizazio epea.' },
      ],
    },
    projects: {
      num: '04',
      title: ['Azken proiektuak,', 'xehetasunez ', 'dokumentatuta.'],
      titleEm: 'dokumentatuta',
      filters: ['Dena', 'Erdialdea', 'Gros', 'Antigua', 'Aiete', 'Lokalak'],
      list: [
        { tag: 'Erreforma integrala', neighbourhood: 'Erdialdea', year: '2025', name: 'Pisu jauntxo San Bartolomén', m2: '142 m²', duration: '4 hilabete', material: 'Mikrozementua + haritza · Aerotermia Daikin' },
        { tag: 'Aerotermia', neighbourhood: 'Gros', year: '2025', name: 'Ganbara Sagüés-eko bistekin', m2: '98 m²', duration: '3 hilabete', material: 'Zoru irradiatzaile freskagarria · Klein zurgintza' },
        { tag: 'Bainugela wellness', neighbourhood: 'Antigua', year: '2024', name: 'Suite nagusia Matian', m2: '18 m²', duration: '5 aste', material: 'Calacatta marmola · Dornbracht txorrota' },
        { tag: 'Lokal komertziala', neighbourhood: 'Erdialdea', year: '2024', name: 'Showroom Elkano 1ean', m2: '85 m²', duration: '6 aste', material: 'Intxaur ohol · Erco argiztapen lineala' },
      ],
    },
    process: {
      num: '05',
      title: ['Nola lan egiten dugun.'],
      steps: [
        { num: '01', title: 'Bisita teknikoa', body: 'Aparejadorea obran. Neurketak, instalazioen egoera eta diagnostiko estrukturala. Konpromisorik gabe.' },
        { num: '02', title: 'Aurreproiektua', body: 'Planoak, kalitate-memoria eta partidaka aurrekontu itxia. Zifra bakar bat, ezustekorik gabe.' },
        { num: '03', title: 'Lizentziak', body: 'Aurretiazko komunikazioa edo obra lizentzia izapidetzen dugu Udalean. Bisatuaren ardura gurea da.' },
        { num: '04', title: 'Exekuzioa', body: 'Zuzendaritza fakultatiboak koordinatutako obra. Asteroko txostenak argazki eta kronogramaren aurrerapenarekin.' },
        { num: '05', title: 'Entrega', body: 'Azken errepasoa, eskuliburuak, instalazio ziurtagiriak eta hamar urteko bermea. Giltzak bezeroari.' },
      ],
    },
    team: {
      num: '06',
      quote: ['"Donostian erreforma egitea ez da azulejoak jartzea.', '1920ko eraikin bat, araudi bat eta', 'zehaztasuna espero duen bezero', 'bat ulertzea da."'],
      quoteEm: 'zehaztasuna',
      author: 'Zuzendaritza teknikoa · Reformas Elkano',
      authorRole: 'ARK · TEK · KOL.',
      trust: [
        { n: '14', label: '2025etik entregatutako proiektuak' },
        { n: '5.0', label: 'Google batez besteko balorazioa' },
        { n: '100', label: '% lizentzia izapidetuta dituzten obrak' },
        { n: '0', label: 'Aurrekontu itxian gainkostu' },
      ],
    },
    contact: {
      num: '07',
      headline: ['Konta iezaguzu zure', 'proiektua. 48 ordu', 'barru ', 'bisitatuko zaitugu.'],
      headlineEm: '48 ordu',
      info: [
        { k: 'Denda fisikoa', v: 'Elkano Kalea 1\n20004 Donostia · Gipuzkoa' },
        { k: 'Telefonoa', v: '651 693 689', link: 'tel:+34651693689' },
        { k: 'Posta', v: 'info@reformaselkano.es', link: 'mailto:info@reformaselkano.es' },
        { k: 'Ordutegia', v: 'A–O · 09:00 – 18:30\nLarunbatean hitzorduarekin' },
      ],
    },
    testimonials: {
      num: '06',
      title: ['Erreforman bizi', 'direnek ', 'diotena.'],
      titleEm: 'diotena',
      list: [
        { quote: 'Sinatutako epea eta aurrekontu itxia egunez egun bete zituzten. Zuzendaritza teknikoa bikaina izan zen: astero genekien obraren puntu zehatza.', author: 'Maria U.', role: 'Etxebizitza · Erdialdea · 138 m²', stars: 5 },
        { quote: 'Galdara aerotermia eta zoru irradiatzailera aldatu genuen eta erosotasunean eta fakturan aldea izugarria da. Eraikinaren ingeniariak baino hobeto aholkatu gintuzten.', author: 'Iñaki B.', role: 'Aerotermia · Gros · 95 m²', stars: 5 },
        { quote: 'Erdialdean denda fisikoa, partidaka aurrekontua eta tratu hurbila. Lau aurrekontu eskatu ondoren, argi hitz egin zigutenak hauek izan ziren.', author: 'Carmen eta Jorge L.', role: 'Erreforma integrala · Antigua', stars: 5 },
        { quote: 'Wellness bainugela harrizko materialekin 18 m²-tan ezinezkoa zirudiena. Akabera ezin hobeak urtebete geroago. Sukaldera itzuliko gara.', author: 'Ane S.', role: 'Bainua · Aiete · 18 m²', stars: 5 },
      ],
    },
    zone: {
      num: '07',
      title: ['Donostia eta', 'inguruak.'],
      lede: 'Gipuzkoa osoan lan egiten dugu, Donostian eta mugakide diren udalerrietan arreta jarrita. Elkano 1eko egoitza fisikoak 48 ordutan baino gutxiagotan bisita teknikoak egiteko aukera ematen digu auzo guztietan.',
      areas: [
        { n: 'Erdialdea', desc: 'Zabalgunea · Erromantizismoa' },
        { n: 'Gros', desc: 'Sagüés · Egia' },
        { n: 'Antigua', desc: 'Ondarreta · Matia' },
        { n: 'Aiete', desc: 'Miramón · Lorea' },
        { n: 'Alde Zaharra', desc: 'Parte Vieja' },
        { n: 'Amara', desc: 'Berri · Anoeta' },
        { n: 'Hernani', desc: 'Astigarraga · Lasarte' },
        { n: 'Errenteria', desc: 'Pasaia · Oiartzun' },
      ],
    },
    faq: {
      num: '08',
      title: ['Ohiko', 'galderak.'],
      list: [
        { q: 'Zenbat balio du erreforma integral batek Donostian?', a: 'Hasierako egoeraren eta akaberen mailaren arabera. Erreferentzia gisa, gama ertain-altuko materialekin eta aerotermiarekin egindako erreforma integral bat 1.200 € eta 1.800 € artean dabil m²-ko. Lehen bisita teknikoan partidaka aurrekontu itxi bat ematen dizugu, ezustekorik gabe.' },
        { q: 'Zer barne hartzen du aurrekontu itxiak?', a: 'Proiektu teknikoa, lizentzien kudeaketa, eraisketa, instalazio guztiak (iturgintza, elektrizitatea, klimatizazioa), igeltserotza, zurgintza, sanitarioak, zoladurak, pintura eta zuzendaritza fakultatiboa biltzen ditu. Aurreikusi gabeko egiturazkoak izanez gero, ezer ukitu aurretik komunikatzen dira.' },
        { q: 'Lizentzia Udalean izapidetzen duzue?', a: 'Bai. Obraren tamainaren arabera, aurretiazko komunikazioa, obra txikiko lizentzia edo obra handirako proiektu tekniko bisatua prestatzen dugu. Donostiako Udalaren epeak eta berezitasunak ezagutzen ditugu.' },
        { q: 'Etxean bizitzen jarrai dezaket obran zehar?', a: 'Erreforma integraletan ez dugu gomendatzen segurtasun eta hauts arrazoiengatik. Bainua edo sukaldea soilik erreformatzen badira, faseak planifikatzen ditugu egon zaitezen. Aldi baterako alokairu baten denbora eta kostua kalkulatzen lagunduko dizugu.' },
        { q: 'Zenbat denbora behar du erreforma integral batek?', a: 'Batez besteko 90–120 m²-ko etxebizitza batek 12 eta 16 aste behar ditu lizentzia eman ondoren. Epea kontratuan sinatzen da eta atzerapenak gure errua badira penalizazioa dakarte.' },
        { q: 'Zer berme ematen duzue?', a: 'Hamar urteko berme dekanala egiturazko elementuetan (Eraikingintzaren Antolamendurako Legea), hiru urte elementu eraikitzaileetan eta urtebete akaberetan. Dokumentazio guztia zure eskuan geratzen da bukatzean.' },
      ],
    },
    footer: {
      legal: ['Lege oharra', 'Pribatutasun politika', 'Cookieak'],
      copy: '© 2025–2026 Reformas Elkano · Elkano Kalea 1, 20004 Donostia',
    },
    marquee: ['Erreforma integralak', 'Aerotermia + zoru irradiatzailea', 'Aparejadore kolegiatuak', 'Aurrekontu itxia', 'Obra handi eta txikia', 'San Sebastián Shops', 'A eraginkortasun energetikoa'],
  },
};

const formCopy = {
  es: {
    name: 'Nombre y apellidos',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    typeLabel: 'Tipo de proyecto',
    typeOptions: ['Vivienda', 'Local', 'Aerotermia', 'Solo baño/cocina'],
    neighLabel: 'Barrio o zona',
    neighPh: 'Centro, Gros, Antiguo…',
    sizeLabel: 'Superficie aproximada',
    sizePh: 'Ej. 95 m²',
    msg: 'Cuéntanos qué tienes en mente',
    msgPh: 'Estado actual de la vivienda, plazos deseados, referencias visuales…',
    submit: 'Enviar solicitud',
    meta: 'Le respondemos en 48 h. laborables.',
  },
  eu: {
    name: 'Izen-abizenak',
    email: 'Posta elektronikoa',
    phone: 'Telefonoa',
    typeLabel: 'Proiektu mota',
    typeOptions: ['Etxebizitza', 'Lokala', 'Aerotermia', 'Bainu/sukalde soilik'],
    neighLabel: 'Auzoa edo gunea',
    neighPh: 'Erdialdea, Gros, Antigua…',
    sizeLabel: 'Gutxi gorabeherako azalera',
    sizePh: 'Adib. 95 m²',
    msg: 'Konta iezaguzu zer duzun buruan',
    msgPh: 'Etxebizitzaren egoera, nahi diren epeak, ikusizko erreferentziak…',
    submit: 'Bidali eskaera',
    meta: '48 ordu lanegunetan erantzungo dizugu.',
  },
};

window.i18n = i18n;
window.formCopy = formCopy;
